<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ETMUM-LT114" name="com.usergroups.tests.GlobalFooterTest" tests="5" failures="4" timestamp="30 Aug 2016 18:23:10 GMT" time="13.636" errors="1">
  <testcase name="testVerifyLandingPage" time="13.632" classname="com.usergroups.tests.GlobalFooterTest">
    <error type="java.lang.AssertionError" message="Title not matched expected [Find Splunk User Groups Anywhere in The World] but found [Find Splunk User Groups Anywhere in The Worlds]">
      <![CDATA[java.lang.AssertionError: Title not matched expected [Find Splunk User Groups Anywhere in The World] but found [Find Splunk User Groups Anywhere in The Worlds]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.usergroups.tests.GlobalFooterTest.testVerifyLandingPage(GlobalFooterTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- testVerifyLandingPage -->
  <testcase name="testVerifyFooterCopyRightsText" time="0.001" classname="com.usergroups.tests.GlobalFooterTest"/>
  <testcase name="testVerifyFooterLinks" time="0.003" classname="com.usergroups.tests.GlobalFooterTest"/>
  <testcase name="testVerifyFooterSplunkUGLink" time="0.000" classname="com.usergroups.tests.GlobalFooterTest"/>
  <testcase name="testVerifyFooterFollowUS" time="0.000" classname="com.usergroups.tests.GlobalFooterTest"/>
</testsuite> <!-- com.usergroups.tests.GlobalFooterTest -->
